# Docker Compose untuk WhatsApp CRM terintegrasi dengan n8n-production
# Sesuai dengan setup yang sudah ada di root/n8n-production/

version: '3.7'

services:
  # WhatsApp CRM AI Assistant
  whatscrm-ai:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your_32_character_key}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/google-credentials.json
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./config:/app/config
      - ./sessions:/app/sessions
      - ./conversations:/app/conversations
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  app-network:
    external: true

volumes:
  postgres_data:
  n8n_data:
  npm_data:
  letsencrypt:
  redis_data: